version: "3.9"
services: 
  backend-app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3005:8080
    environment: 
      PORT: 8080
    volumes:
      - ./:/server:ro
    depends_on: 
      - fm-mongo

  fm-mongo:
    image: mongo
    restart: always
    volumes: 
      - /home/nikolay/Documents/mongodata:/data/db